import type { Artwork } from "./types"

export const myArtwork: Artwork[] = [
  {
    id: "81",
    title: "Quick Sketch- Tails",
    image: "/art/tails.png",
    description: "Sketch of tails from the sonic series.",
    date: "19 November 2025",
    software: "Krita",
    genre: "Fan Art",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "80",
    title: "Yareli",
    image: "/art/yareli/yareli line.png",
    images: [
      "/art/yareli/yareli line.png",
      "/art/yareli/yareli no line.png",
    ],
    description: "A drawing of the character Yareli from Warframe.",
    date: "22 September 2025",
    software: "Krita",
    genre: "Character Design",
    isDigital: true,
    isFavorite: false,
    timeTaken: "6h 1m",
  },
  {
    id: "79",
    title: "Quick Sketch- Ai Ohto",
    image: "/art/ai ohto.png",
    description: "A drawing of Ai Ohto from wonder egg priority, not heavily rendered, just wanted to draw her for fun.",
    date: "19 June 2025",
    software: "Krita",
    genre: "Fan Art",
    isDigital: true,
    isFavorite: false,
    timeTaken: "4h 17min",
  },
  {
    id: "78",
    title: "Quick Sketch- Chao",
    image: "/art/Chao.png",
    description: "A cute lil Chao from the sonic series.",
    date: "14 June 2025",
    software: "Krita",
    genre: "Character Design",
    isDigital: true,
    isFavorite: false,
    timeTaken: "1h 8m",
  },
  {
    id: "77",
    title: "Gura",
    image: "/art/Gura.png",
    description: "I dont watch Vtubers, but i saw a cool drawing of this one and wanted to recreate it.",
    date: "05 May 2025",
    software: "Krita",
    genre: "Fan Art",
    isDigital: true,
    isFavorite: true,
    timeTaken: "5h 49m",
  },
  {
    id: "76",
    title: "Empty",
    image: "/art/empty/empty v2.png",
    images: [
      "/art/empty/empty v2.png",
      "/art/empty/empty.png",
    ],
    description: "An emotional drawing. Final version vs first draft.",
    date: "13 April 2025",
    software: "Krita",
    genre: "Character Design",
    isDigital: true,
    isFavorite: false,
    timeTaken: "4h 44m",
  },
  {
    id: "75",
    title: "Quick Sketch- Hollow Knight and Hornet",
    image: "/art/hollow.png",
    description: "I had just beaten hollow knight and wanted to them. Just a quick sketch with a simple background.",
    date: "13 April 2025",
    software: "Krita",
    genre: "Illustration",
    isDigital: true,
    isFavorite: false,
    timeTaken: "1h 51m",
  },
  {
    id: "74",
    title: "Quick Sketch- Neon City",
    image: "/art/neon city.png",
    description: "A purple neon city with some fog.",
    date: "22 March 2025",
    software: "Krita",
    genre: "Environment",
    isDigital: true,
    isFavorite: false,
    timeTaken: "1h 29m",
  },
  {
    id: "73",
    title: "Innocence Forged in Fire",
    image: "/art/Innocence forged in fire.png",
    description: "My first completely original drawing with no 1 for 1 references. The simple story behind this follows that of a fiery demon who crawled out of hell, and he encounters a little cat. Yet curiously he doesn't attack or scare it away, but goes down to pet it.",
    date: "24 November 2024",
    software: "Krita",
    genre: "Concept Art",
    isDigital: true,
    isFavorite: true,
    timeTaken: "2h 44m",
  },
  {
    id: "72",
    title: "Crucible Knight Starscape",
    image: "/art/crucible stars.png",
    description: "This is based off a scene from elden ring, where an esteemed and estranged \"Crucible Knight\" stares off into the underground expanse filled with shiny rocks that mimics nebula.",
    date: "24 September 2024",
    software: "Krita",
    genre: "Environment",
    isDigital: true,
    isFavorite: false,
    timeTaken: "35mins",
  },
  {
    id: "71",
    title: "The Lich- Furnace Pose",
    image: "/art/lich.png",
    description: "A drawing of the Lich from adventure time, pose inspired by sukuna from Jujutsu Kaisen.",
    date: "04 September 2024",
    software: "Krita",
    genre: "Character Design",
    isDigital: true,
    isFavorite: false,
    timeTaken: "1h 58m",
  },
  {
    id: "70",
    title: "Raiden and 2b",
    image: "/art/raiden2b.png",
    description: "Crossover fan art featuring Raiden from Metal Gear Revengance and 2b from Neir Autonoma.",
    date: "16 May 2024",
    software: "Krita",
    genre: "Fan Art",
    isDigital: true,
    isFavorite: false,
    timeTaken: "6h 41m",
  },
    {
    id: "69",
    title: "Random Girl 1",
    image: "/art/uhh.jpg",
    description: "Idk.",
    date: "14 April 2024",
    software: "Krita",
    genre: "Sketch",
    isDigital: true,
    isFavorite: false,
    timeTaken: "2h 59m",
  },
  {
    id: "68",
    title: "Sonic vs Metal Sonic",
    image: "/art/sonic.png",
    description: "My first drawing after switching from Sketchbook to Krita, oh yeah it was a good idea to move.",
    date: "17 December 2023",
    software: "Krita",
    genre: "Fan Art",
    isDigital: true,
    isFavorite: true,
  },
  {
    id: "67",
    title: "Sonic",
    image: "/art/drawing17.tif",
    description: "My last completed drawing on sketchbook",
    date: "30 July 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "66",
    title: "Quick Sketch- Neon Nezuko",
    image: "/art/drawing16.tif",
    description: "Another quick neon test with a demon slayer character.",
    date: "28 July 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "65",
    title: "Neon Deku- Power pose",
    image: "/art/drawing15.tif",
    description: "This is where i started to experiment with neon effects in characters, clearly i have a long way to go. This was insired by Izuku from My Hero Academia",
    date: "26 May 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "64",
    title: "Rengoku",
    image: "/art/drawing14.tif",
    description: "This digital art was a redrawing of one i had done with pencil and paper before, testing how different media differently convey my drawings.",
    date: "04 May 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "63",
    title: "Shinobu in a Wysteria flower garden",
    image: "/art/drawing13.tif",
    description: "I wanted to draw something from demon slayer, so i drew shinobu.",
    date: "25 April 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "62",
    title: "Romani/Malon riding a horse",
    image: "/art/drawing12.tif",
    description: "I just wanted to draw something legend of zelda related after beating Ocarina of Time and Majoras Mask half a year prior. I have no clue if this is romani or malon as they are look the same and are basically counterparts paralleling between the games.",
    date: "06 April 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "61",
    title: "Random girl 3",
    image: "/art/drawing11.tif",
    description: "This drawing (yes i know the face is wonky) was inspired by an image that would show on a manga website when a chapter hadn't released yet. I had more time and boredom back then.",
    date: "18 March 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "60",
    title: "Sans and Frisk in Judgement Hall",
    image: "/art/drawing9.tif",
    description: "This cute little piece was one i took reference from TC-96s drawing, an artist whos undertale comics i heavily followed in my childhood. It depicts sans and frisk sharing a nice nap in the judgement hall, this is sure to spark emotions in anyone who knows how the situation could turn out differently under worse conditions.",
    date: "13 March 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "59",
    title: "Sans attacking",
    image: "/art/drawing10.tif",
    description: "A powerful magic attack casted by sans as a last resort.",
    date: "12 March 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "58",
    title: "Deku- Menacing",
    image: "/art/drawing8.tif",
    description: "Okay yeah the stars alligned with this one, the use of simple shapes and lighting boosted this piece well beyond my skill level at the time, as seen comparing this to my other works. This picture of Deku/Izuku Midoriya was inspired by a tournament fight.",
    date: "10 February 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: true,
  },
  {
    id: "57",
    title: "Random Girl 2",
    image: "/art/drawing7.tif",
    description: "A return to colouring after practicing just line art.",
    date: "08 February 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "56",
    title: "Megumin",
    image: "/art/drawing6.tif",
    description: "Megumin from Konosuba.",
    date: "14 January 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "55",
    title: "Irina Jelavić",
    image: "/art/drawing5.tif",
    description: "Irina Jelavić from Classroom Assasination.",
    date: "02 January 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "54",
    title: "Ai Ohto- Surprised",
    image: "/art/drawing4.tif",
    description: "Ai Ohto from Wonder Egg Priority, but surpsied.. i think.",
    date: "01 January 2023",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "53",
    title: "Ai Ohto- Rahh angry",
    image: "/art/drawing3.tif",
    description: "Ai Ohto from Wonder Egg Priority, but angry.",
    date: "31 December 2022",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "52",
    title: "Ochako Uraraka",
    image: "/art/drawing2.tif",
    description: "Ochako from My Hero Academia.",
    date: "30 December 2022",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },
  {
    id: "51",
    title: "First Digital Drawing- Master Chief's Helmet",
    image: "/art/drawing.tif",
    description: "My first ever digital drawing, Master chiefs helmet.",
    date: "27 December 2022",
    software: "Sketchbook",
    genre: "Study",
    isDigital: true,
    isFavorite: false,
  },

  // Placeholders 50-1
  // {
  //   id: "50",
  //   title: "Placeholder 50",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "49",
  //   title: "Placeholder 49",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "48",
  //   title: "Placeholder 48",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "47",
  //   title: "Placeholder 47",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "46",
  //   title: "Placeholder 46",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "45",
  //   title: "Placeholder 45",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "44",
  //   title: "Placeholder 44",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "43",
  //   title: "Placeholder 43",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "42",
  //   title: "Placeholder 42",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "41",
  //   title: "Placeholder 41",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "40",
  //   title: "Placeholder 40",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "39",
  //   title: "Placeholder 39",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "38",
  //   title: "Placeholder 38",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "37",
  //   title: "Placeholder 37",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "36",
  //   title: "Placeholder 36",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "35",
  //   title: "Placeholder 35",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "34",
  //   title: "Placeholder 34",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "33",
  //   title: "Placeholder 33",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "32",
  //   title: "Placeholder 32",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "31",
  //   title: "Placeholder 31",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "30",
  //   title: "Placeholder 30",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "29",
  //   title: "Placeholder 29",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "28",
  //   title: "Placeholder 28",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "27",
  //   title: "Placeholder 27",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "26",
  //   title: "Placeholder 26",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "25",
  //   title: "Placeholder 25",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "24",
  //   title: "Placeholder 24",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "23",
  //   title: "Placeholder 23",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "22",
  //   title: "Placeholder 22",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "21",
  //   title: "Placeholder 21",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "20",
  //   title: "Placeholder 20",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "19",
  //   title: "Placeholder 19",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "18",
  //   title: "Placeholder 18",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "17",
  //   title: "Placeholder 17",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "16",
  //   title: "Placeholder 16",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "15",
  //   title: "Placeholder 15",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "14",
  //   title: "Placeholder 14",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "13",
  //   title: "Placeholder 13",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "12",
  //   title: "Placeholder 12",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "11",
  //   title: "Placeholder 11",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "10",
  //   title: "Placeholder 10",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "9",
  //   title: "Placeholder 9",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "8",
  //   title: "Placeholder 8",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "7",
  //   title: "Placeholder 7",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "6",
  //   title: "Placeholder 6",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "5",
  //   title: "Placeholder 5",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "4",
  //   title: "Placeholder 4",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "3",
  //   title: "Placeholder 3",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "2",
  //   title: "Placeholder 2",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
  // {
  //   id: "1",
  //   title: "Placeholder 1",
  //   image: "/art/placeholder.png",
  //   description: "Placeholder description",
  //   date: "01 January 2000",
  //   software: "Other",
  //   genre: "Sketch",
  //   isDigital: false,
  //   isFavorite: false,
  // },
]

export const secretArtwork: Artwork[] = []
